[package]
name = "primesieve-sys"
version = "0.1.0"
edition = "2021"
description = "FFI bindings to primesieve 8.0"
links = "primesieve"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
pkg-config = "0.3.24"
