[package]
name = "calculation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-time = "1.0.0"
itertools = "0.10.3"
num_cpus = "1.13.0"
primesieve = { path = "../primesieve" }
rayon = "1.5.1"
